name: Leandro Lobosco
favicon: null
layout_spectrum: 0.2687758158426732
typography_spectrum: 0.019365765852853656
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.19610934774391353
  lightness: 0.795732227852568
  saturation: 0.0764973103068769
  rhythmicContrast: 0.37527232337743044
purpose: []
